version: '3.0'
services:
    rasa-server:
      image: rasa-server-okteto:latest
      build: './'
      volumes:
      - ./:/app
      - ./data:/app/data
      - ./models:/app/models
      ports: 
      - '5006:5005'
      public: true
      depends_on:
      - action-server
      command:
      - run
      - --cors
      - "*"
      - --enable-api
      - -p 5006
      - -m models/20220624-154440-fat-dingo.tar.gz
      working_dir: /app
      networks:
      - all

    action-server:
      image: rasa-server-okteto:latest
      build: './'
      volumes:
      - ./actions:/app/actions
      ports:
      - '5055:5055'
      command: run actions
      working_dir: /app
      networks:
      - all

networks:
  all: bridge
  driver_opts:
    com.docker.network.enable.ipv6: true