version: '3.0'
services:
    rasa-server:
      container_name: "rasa-server"
      build: 
        context: .
      volumes:
      - "./:/app"
      ports: 
        - "5006:5005"
      command:
        - run
      public: true
      restart: always
      depends_on:
        - action-server 

    action-server:
      container_name: "action-server"
      build: 
        context: actions
      volumes:
        - ./actions:/app/actions
        - ./data:/app/data
      ports:
        - "5055:5055"
      command:
        - start