version: '3.0'
services:
    rasa-server:
      image: rasa/rasa:3.1.0-full
      build: './'
      volumes:
      - ./:/app
      ports: 
      - '5006:5005'
      public: true
      depends_on:
      - action-server
      command:
      - run
      - --cors
      - "*"
      - --enable-api
      - -p 5006
      - -m models/20220624-154440-fat-dingo.tar.gz
      working_dir: /app

    action-server:
      image: rasa/rasa-sdk:3.1.1
      build: './'
      volumes:
      - ./actions:/app/actions
      ports:
      - '5055:5055'
      command: run actions
      working_dir: /app