version: '3.0'
services:
    rasa-server:
      image: rasa:3.1.0-full
      build: './'
      volumes:
      - ./:/app
      ports: 
      - '5006:5005'
      public: true
      depends_on:
      - action-server
      command: rasa run --enable-api
      working_dir: /app

    action-server:
      image: rasa-sdk:3.1.1
      build: './'
      volumes:
      - ./actions:/app/actions
      ports:
      - '5055:5055'
      command: bash -c "rasa run actions"
      working_dir: /app