version: '3.0'
services:
    rasa-server:
      image: rasa/rasa:3.1.0-full
      working_dir: /app
      build: './'
      restart: always
      volumes:
      - ./actions:/app/actions
      - ./data:/app/data
      command: ["run", "--enable-api", "--cors", "\"*\"", "--debug"]
      ports: 
      - '5006:5005'
      public: true
      networks:
      - all

    action-server:
      image: rasa/rasa-sdk:3.1.1
      working_dir: /app
      build: './'
      restart: always
      volumes:
      - ./actions:/app/actions
      - ./utils:/app/utils
      command: ["run", "actions"]
      ports:
      - '5055:5055'
      networks:
      - all

networks:
  all: bridge
  driver_opts:
    com.docker.network.enable.ipv6: "true"